/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kapi

import com.kapi.exposed.psql.initialize
import org.koin.core.context.startKoin

import io.ktor.server.engine.*
import io.ktor.server.netty.*

import com.kapi.server.routeFindRestaurants;
import com.kapi.server.routeCreateReservation;
import io.ktor.server.routing.*

fun main() {
    initialize()
    startKoin {
        modules(appModule)
    }
    embeddedServer(Netty, port = 8080) {
        routing {
            get("/restaurant/find") { routeFindRestaurants() }
            post("/reservation") { routeCreateReservation() }
        }
    }.start(wait = true)
}