/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kapi

import com.kapi.exposed.psql.initialize
import org.koin.core.context.startKoin

import io.ktor.server.engine.*
import io.ktor.server.netty.*

import com.kapi.server.routeFindRestaurants;
import com.kapi.server.routeCreateReservation;
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.application.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.server.routing.*
import kotlinx.serialization.json.Json

fun main() {
    initialize()
    startKoin {
        modules(appModule)
    }
    embeddedServer(Netty, port = 8080) {
        install(ContentNegotiation) {
            json(Json {
                prettyPrint = true
                isLenient = true
            })
        }
        routing {
            get("/restaurant/find") { routeFindRestaurants() }
            post("/reservation") { routeCreateReservation() }
        }
    }.start(wait = true)
}